meson.build: fix build race when building GTK vapi files
There's a build race when building the GTK vapi files:

FAILED: libportal/libportal-gtk4.vapi
error: Package `libportal' not found in specified Vala API directories or GObject-Introspection GIR directories

This can be verified by adding "sleep 10;" to the command for the
libportal/libportal.vapi target in the generated build.ninja file.

The GTK vapi files need to have access to the generic libportal.vapi file,
but there is no explicit dependency.  Switch the dependency name 'libportal'
to the dependency object libportal_vapi so that Meson generates the
dependency correctly.

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>